gpu_exist: true
device_id: 0
batch_size: 32
hidden_size: 1024
embedding_size: 30
bidirectional: false
epochs: 100
nr_classes: 4
predict_prop: true
nr_prop: 1
rnn_type: 'gru'
learning_rate: 0.001
latent_size: 512
n_layers: 1
save_every: 10
word_dropout: 0.1
vocab_size: 79
anneal_function: 'logistic'
k0: .0025
x0: 5000
save_dir: ''
